name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -H. -B build -DCMAKE_INSTALL_PREFIX=build/artifacts

      - name: Build
        run: cmake --build build

      - name: Install
        run: cmake --build build --target install

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifacts
          path: build/artifacts/
