name: C++ CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        if ["${{ matrix.os }}" == "ubuntu-latest"] ; then
          sudo apt-get update
          sudo apt-get install -y cmake make g++
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          brew install cmake
        fi

    - name: Configure CMake
      run: |
        rm -rf ${{github.workspace}}/build
        mkdir ${{github.workspace}}/build
        cmake -B ${{github.workspace}}/build -S ${{github.workspace}}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build

    - name: Package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cpack -G DEB
        cpack -G RPM
        cpack -G WIX
        cpack -G DragNDrop

    - name: Upload artifacts
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v2
      with:
        name: solver-packages
        path: |
          ${{github.workspace}}/build/*.deb
          ${{github.workspace}}/build/*.rpm
          ${{github.workspace}}/build/*.msi
          ${{github.workspace}}/build/*.dmg
