name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make g++

    - name: Configure CMake
      run: |
        rm -rf ${{github.workspace}}/build
        mkdir ${{github.workspace}}/build
        cmake -B ${{github.workspace}}/build -S ${{github.workspace}}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.7
      with:
        cmake-version: '3.18.2'

    - name: Configure CMake
      run: |
        rm -rf ${{github.workspace}}/build
        mkdir ${{github.workspace}}/build
        cmake -B ${{github.workspace}}/build -S ${{github.workspace}}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build

    - name: Package
      run: |
        cpack -G DEB
        cpack -G RPM
        cpack -G WIX
        cpack -G DragNDrop

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: solver-packages
        path: |
          *.deb
          *.rpm
          *.msi
          *.dmg
