name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
        run: |
          cmake -H. -B build -DCMAKE_INSTALL_PREFIX=_install
          cmake --build  build
          cmake --build  build --target install


